name: 'Close stale issues and PR'
on:
  workflow_dispatch:
  schedule:
    - cron: '30 1 * * *' # https://crontab.guru/#30_1_*_*_* (everyday at 0130)

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@02989dcb65055c8fd08a5dec9332c1279c8e2639 # (latest, untagged)
        with:
          operations-per-run: 200
          ascending: true
          delete-branch: true
          stale-issue-message: >
            This issue is stale because it has been open 10 days with no activity.
            Replace the `no-issue-activity` label with a `work-in-progress` label or comment or
            this will be closed in 5 days.
          close-issue-message: >
            This issue was closed because it has been stalled for 5 days with no activity.
          days-before-issue-stale: 10
          days-before-issue-close: 5
          stale-issue-label: 'no-issue-activity'
          exempt-issue-labels: 'awaiting-approval,work-in-progress'
          stale-pr-message: >
            This PR is stale because it has been open 20 days with no activity.
            Replace the `no-pr-activity` label with a `work-in-progress` label or comment or
            this will be closed in 5 days.
          close-pr-message: >
            This PR was closed because it has been stalled for 5 days with no activity.
          days-before-pr-stale: 20
          days-before-pr-close: 5
          stale-pr-label: 'no-pr-activity'
          exempt-pr-labels: 'awaiting-approval,work-in-progress,dependencies'
